### ISSUE TITLE
Fails to take .jscpd.json for JSCPD

### ISSUE THREAD

**Issue by amjltc295** [github/super-linter#1331]
## Describe the bug

super-linter does not take the config (e.g. threshold) in .jscpd.json, making the CI failed

## Expected behavior

Take the threshold in .jscpd.json and pass CI

## Steps to Reproduce
(local)
docker run -e RUN_LOCAL=true -e VALIDATE_JAVASCRIPT_ES=false -e VALIDATE_HTML=false -e JSCPD_CONFIG_FILE='.jscpd.json' -v /Users/allen.c/Dako/CompanyWebsite:/tmp/lint github/super-linter

## Logs

```
Run github/super-linter@v3
  env:
    VALIDATE_JAVASCRIPT_ES: false
    VALIDATE_HTML: false
    JSCPD_CONFIG_FILE: .jscpd.json
    DEFAULT_BRANCH: main
    GITHUB_TOKEN: ***
/usr/bin/docker run --name ghcriogithubsuperlinterv3145_2f07cd --label 5588e4 --workdir /github/workspace --rm -e VALIDATE_JAVASCRIPT_ES -e VALIDATE_HTML -e JSCPD_CONFIG_FILE -e DEFAULT_BRANCH -e GITHUB_TOKEN -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/CompanyWebsite/CompanyWebsite":"/github/workspace" ghcr.io/github/super-linter:v3.14.5

...

ERROR: jscpd found too many duplicates (3.67%) over threshold (0%)
Error: ERROR: jscpd found too many duplicates (3.67%) over threshold (0%)
    at ThresholdReporter.report (/node_modules/@jscpd/finder/dist/reporters/threshold.js:12:19)
    at /node_modules/@jscpd/finder/dist/in-files-detector.js:82:26
    at Array.forEach (<anonymous>)
    at /node_modules/@jscpd/finder/dist/in-files-detector.js:81:28
```

.jscpd.json
```
{
  "threshold": 10,
  "reporters": [
    "html",
    "console",
    "badge"
  ],
  "ignore": [
    "**/__snapshots__/**"
  ],
  "absolute": true,
  "gitignore": true
}

**Comment by amjltc295** [comment]
@GaboFDC no power here :(

**Comment by GaboFDC** [comment]
Bot is mad with power 😅 

About your issue, yo need to use the `LINTER_RULES_PATH: /` for the linter to take the config files from the root directory. Or you can also put the file under `.github/linters`

**Comment by amjltc295** [comment]
Ohhh I did not notice that var, thank you very much!
