### ISSUE TITLE
Superlinter .jscpd.json file ignore is not working 

### ISSUE THREAD

**Issue by dhananjayagupta** [github/super-linter#2198]
## Describe the bug

I am trying keep to exclude the files from jscpd scanning but its not working even after correct configuration. Please refer to the ignore section of below config.

My Configuration for files are :

**File:** <REPO_NAME>/.github/linters/.jscpd.json
```
{
  "hasModules": false,
  "threshold": 0,
  "configurations": {
    "reporters": [ "html", "verbose" ],
    "format": [
      "csharp",
      "typescript",
      "javascript",
      "java",
      "cpp",
      "c"
    ],
    "ignore": [ "**/.github/**", "**/*.yml", "**/github/workspace/.github/workflows/**" ],
    "min-tokens": 200,
    "absolute": true
  }
}
```
**Action File:**
```
jobs:
  Static_Code_Checks:
    # Name the Job
    name: Static_Code_Checks
    runs-on: [self-hosted, my-runner ] 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PSI2M_ACCESS_TOKEN }}
          
      - name: JSCPD Scanner
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JSCPD: true
          FILTER_REGEX_EXCLUDE: .**/CICD/**
          LINTER_RULES_PATH: .github/linters
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
```
## Expected behavior

It should ignore the files which I have mentioned under ignore section of .jscpd.json config file.

```
"ignore": [ "**/.github/**", "**/*.yml", "**/github/workspace/.github/workflows/**" ],
```

## Steps to Reproduce

1. Go to gihub repo
1. Create workflow and use block for super linter as mentioned in "Describe the bug"
1. Run the workflow.
1. See error

## Logs

![image](https://user-images.githubusercontent.com/88882117/144389776-03502dc2-5517-4a3b-a1d0-39ecfe1fa37c.png)
```
2021-12-02 08:44:28 [INFO]   --- GitHub Actions Multi Language Linter ----
2021-12-02 08:44:28 [INFO]    - Image Creation Date:[]
2021-12-02 08:44:28 [INFO]    - Image Revision:[563be7dc5568017515b9e700329e9c6d3862f2b7]
2021-12-02 08:44:28 [INFO]    - Image Version:[563be7dc5568017515b9e700329e9c6d3862f2b7]
2021-12-02 08:44:28 [INFO]   ---------------------------------------------
2021-12-02 08:44:28 [INFO]   ---------------------------------------------
2021-12-02 08:44:28 [INFO]   The Super-Linter source code can be found at:
2021-12-02 08:44:28 [INFO]    - https://github.com/github/super-linter
2021-12-02 08:44:28 [INFO]   ---------------------------------------------
Removing Languages from LANGUAGE_ARRAY for slim image...
found item:[ARM], removing Language...
found item:[CSHARP], removing Language...
found item:[ENV], removing Language...
found item:[POWERSHELL], removing Language...
found item:[RUST_2015], removing Language...
found item:[RUST_2018], removing Language...
found item:[RUST_CLIPPY], removing Language...
Removing Linters from LINTER_NAMES_ARRAY for slim image...
found item:[ARM], removing linter...
found item:[CSHARP], removing linter...
found item:[ENV], removing linter...
found item:[POWERSHELL], removing linter...
found item:[RUST_2015], removing linter...
found item:[RUST_2018], removing linter...
found item:[RUST_CLIPPY], removing linter...
2021-12-02 08:44:28 [INFO]   --------------------------------------------
2021-12-02 08:44:28 [INFO]   Gathering GitHub information...
2021-12-02 08:44:28 [INFO]   Successfully found:[GITHUB_SHA], value:[32b6d5d1a7bdd1b1dfd709f4e229303724c28693]
2021-12-02 08:44:28 [INFO]   Successfully found:[GITHUB_WORKSPACE], value:[/github/workspace]
2021-12-02 08:44:28 [INFO]   Successfully found:[GITHUB_EVENT_PATH], value:[/github/workflow/event.json]
2021-12-02 08:44:28 [INFO]   Successfully found:[GITHUB_ORG], value:[philips-test-org]
2021-12-02 08:44:28 [INFO]   Successfully found:[GITHUB_REPO], value:[PSI2M-IoT_RSM.AuditTrail]
2021-12-02 08:44:28 [INFO]   Successfully found:[GITHUB_TOKEN]
2021-12-02 08:44:28 [INFO]   Successfully found:[GITHUB_REPOSITORY], value:[philips-test-org/PSI2M-IoT_RSM.AuditTrail]
2021-12-02 08:44:28 [INFO]   Successfully found:[GITHUB_RUN_ID], value:[1529729613]
2021-12-02 08:44:28 [INFO]   --------------------------------------------
2021-12-02 08:44:28 [INFO]   Gathering user validation information...
2021-12-02 08:44:28 [INFO]   - Only validating [new], or [edited] files in code base...
2021-12-02 08:44:29 [INFO]   ----------------------------------------------
2021-12-02 08:44:29 [INFO]   User provided file:[/github/workspace/.github/linters/.ansible-lint.yml] exists, setting rules file...
2021-12-02 08:44:29 [INFO]   ----------------------------------------------
2021-12-02 08:44:29 [INFO]   User provided file:[/github/workspace/.github/linters/.dockerfilelintrc] exists, setting rules file...
2021-12-02 08:44:29 [INFO]   ----------------------------------------------
2021-12-02 08:44:29 [INFO]   User provided file:[/github/workspace/.github/linters/actionlint.yml] exists, setting rules file...
2021-12-02 08:44:29 [INFO]   ----------------------------------------------
2021-12-02 08:44:29 [INFO]   User provided file:[/github/workspace/.github/linters/.gitleaks.toml] exists, setting rules file...
2021-12-02 08:44:30 [INFO]   ----------------------------------------------
2021-12-02 08:44:30 [INFO]   User provided file:[/github/workspace/.github/linters/.jscpd.json] exists, setting rules file...
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

2021-12-02 08:44:34 [INFO]   ---------------------------------
2021-12-02 08:44:34 [INFO]   ------ File list to check: ------
2021-12-02 08:44:34 [INFO]   ---------------------------------
2021-12-02 08:44:34 [INFO]   ----------------------------------------------
2021-12-02 08:44:34 [INFO]   Successfully gathered list of files...
2021-12-02 08:44:34 [INFO]   
2021-12-02 08:44:34 [INFO]   ----------------------------------------------
2021-12-02 08:44:34 [INFO]   ----------------------------------------------
2021-12-02 08:44:34 [INFO]   Linting [JSCPD] files...
2021-12-02 08:44:34 [INFO]   ----------------------------------------------
2021-12-02 08:44:34 [INFO]   ----------------------------------------------
2021-12-02 08:44:34 [INFO]   ---------------------------
2021-12-02 08:44:34 [INFO]   File:[/github/workspace/.github/workflows/PR_pipeline.yml]
2021-12-02 08:44:37 [ERROR]   Found errors in [jscpd] linter!
2021-12-02 08:44:37 [ERROR]   Error code: 1. Command output:
------
Clone found (yaml):
 - .github/workflows/PR_pipeline.yml [124:5 - 133:16] (9 lines, 90 ***s)
   .github/workflows/PR_pipeline.yml [96:5 - 105:2]

Clone found (yaml):
 - .github/workflows/PR_pipeline.yml [153:5 - 176:4] (23 lines, 188 ***s)
   .github/workflows/PR_pipeline.yml [122:5 - 145:10]

┌────────┬────────────────┬─────────────┬──────────────┬──────────────┬──────────────────┬───────────────────┐
│ Format │ Files analyzed │ Total lines │ Total ***s │ Clones found │ Duplicated lines │ Duplicated ***s │
├────────┼────────────────┼─────────────┼──────────────┼──────────────┼──────────────────┼───────────────────┤
│ yaml   │ 1              │ 181         │ 1273         │ 2            │ 32 (17.68%)      │ 278 (21.84%)      │
├────────┼────────────────┼─────────────┼──────────────┼──────────────┼──────────────────┼───────────────────┤
│ Total: │ 1              │ 181         │ 1273         │ 2            │ 32 (17.68%)      │ 278 (21.84%)      │
└────────┴────────────────┴─────────────┴──────────────┴──────────────┴──────────────────┴───────────────────┘
Found 2 clones.
ERROR: jscpd found too many duplicates (17.68%) over threshold (0%)
Error: ERROR: jscpd found too many duplicates (17.68%) over threshold (0%)
    at ThresholdReporter.report (/node_modules/@jscpd/finder/dist/reporters/threshold.js:12:19)
    at /node_modules/@jscpd/finder/dist/in-files-detector.js:82:26
    at Array.forEach (<anonymous>)
    at /node_modules/@jscpd/finder/dist/in-files-detector.js:81:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
------
2021-12-02 08:44:37 [INFO]   ---------------------------
2021-12-02 08:44:37 [INFO]   File:[/github/workspace/audit-trail/src/main/java/com/philips/rsm/audit/error/ErrorResponse.java]
2021-12-02 08:44:38 [INFO]    - File:[ErrorResponse.java] was linted with [jscpd] successfully
2021-12-02 08:44:38 [INFO]   ----------------------------------------------
2021-12-02 08:44:38 [INFO]   ----------------------------------------------
2021-12-02 08:44:38 [INFO]   The script has completed
2021-12-02 08:44:38 [INFO]   ----------------------------------------------
2021-12-02 08:44:38 [INFO]   ----------------------------------------------
2021-12-02 08:44:38 [ERROR]   ERRORS FOUND in JSCPD:[1]
2021-12-02 08:44:39 [FATAL]   Exiting with errors found!
```

**Comment by ferrarimarco** [comment]
Hi @dhananjayagupta 

Does that configuration file work if you run JSCPD manually, outside super-linter?

**Comment by shicholas** [comment]
I think it might be related to https://github.com/kucherenko/jscpd/issues/496

**Comment by unixorn** [comment]
I'm seeing this running `github/super-linter@v4` today
