### ISSUE TITLE
Trivy workflow errors when uploading the report if the build failed and the Trivy scan results aren't available

### ISSUE THREAD

**Issue by ferrarimarco** [github/super-linter#2219]
## Describe the bug

Trivy workflow errors when uploading the report if the build failed and the Trivy scan results aren't available. This swallows previous build errors.

This is probably due to https://github.com/github/super-linter/blob/e4b08ec8421c41212d15c4506d129a27ec69b43f/.github/workflows/trivy.yml#L45

## Expected behavior

https://github.com/github/super-linter/blob/e4b08ec8421c41212d15c4506d129a27ec69b43f/.github/workflows/trivy.yml#L43-L47

Shouldn't run if the report generation step didn't run.

## Logs

From: https://github.com/github/super-linter/runs/4469925991?check_suite_focus=true

```
Error: Path does not exist: report.sarif
Error: Path does not exist: report.sarif
    at getSarifFilePaths (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-lib.js:145:15)
    at Object.uploadFromActions (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-lib.js:133:30)
    at run (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-sarif-action.js:50:47)
    at async runWrapper (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-sarif-action.js:67:9)
```

## Additional context

Assigning this to @zkoppert because he worked on this first in #1455

**Comment by nvuillam** [comment]
tip for the neighbours: increase timeout on trivy job :)

https://github.com/megalinter/megalinter/blob/ce0acefc99b653330ea8b7e415e8913db4c2f681/.github/workflows/deploy-DEV.yml#L209
