### ISSUE TITLE
YAML File diff parser errors on Jinja yaml (v3 super linter)

### ISSUE THREAD

**Issue by tinder-yukisawa** [github/super-linter#432]
This does not happen with v2 but started occuring with v3. The linter throws this error in the logs in the initial phase that detects which files have been changed. I don't think the parser likes the Jinja syntax which includes `%`.
```
2020-07-16T17:07:51.5739725Z Files that have been modified in the commit(s):
2020-07-16T17:07:51.5761613Z File:[.github/linters/.yaml-lint.yml], File_type:[yml]
2020-07-16T17:07:51.7108819Z File:[.github/workflows/label.yml], File_type:[yml]
2020-07-16T17:07:51.8382638Z File:[.github/workflows/linter.yaml], File_type:[yaml]
2020-07-16T17:07:52.1140058Z File:[myjinja/config_table.yaml], File_type:[yaml]
2020-07-16T17:07:52.1624923Z Traceback (most recent call last):
2020-07-16T17:07:52.1627732Z   File "/usr/local/bin/shyaml", line 8, in <module>
2020-07-16T17:07:52.1628052Z     sys.exit(entrypoint())
2020-07-16T17:07:52.1628934Z   File "/usr/local/lib/python3.8/site-packages/shyaml.py", line 804, in entrypoint
2020-07-16T17:07:52.1629048Z     sys.exit(main(sys.argv[1:]))
2020-07-16T17:07:52.1629329Z   File "/usr/local/lib/python3.8/site-packages/shyaml.py", line 775, in main
2020-07-16T17:07:52.1629458Z     for output in do(stream=sys.stdin, **opts):
2020-07-16T17:07:52.1629725Z   File "/usr/local/lib/python3.8/site-packages/shyaml.py", line 655, in do
2020-07-16T17:07:52.1629849Z     for content in yaml.load_all(stream, Loader=loader):
2020-07-16T17:07:52.1630144Z   File "/usr/local/lib/python3.8/site-packages/yaml/__init__.py", line 130, in load_all
2020-07-16T17:07:52.1630267Z     yield loader.get_data()
2020-07-16T17:07:52.1630542Z   File "/usr/local/lib/python3.8/site-packages/yaml/constructor.py", line 45, in get_data
2020-07-16T17:07:52.1630670Z     return self.construct_document(self.get_node())
2020-07-16T17:07:52.1631089Z   File "/usr/local/lib/python3.8/site-packages/yaml/composer.py", line 27, in get_node
2020-07-16T17:07:52.1631209Z     return self.compose_document()
2020-07-16T17:07:52.1631488Z   File "/usr/local/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
2020-07-16T17:07:52.1631609Z     node = self.compose_node(None, None)
2020-07-16T17:07:52.1631881Z   File "/usr/local/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
2020-07-16T17:07:52.1632155Z     node = self.compose_mapping_node(anchor)
2020-07-16T17:07:52.1632430Z   File "/usr/local/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
2020-07-16T17:07:52.1632555Z     item_value = self.compose_node(node, item_key)
2020-07-16T17:07:52.1632818Z   File "/usr/local/lib/python3.8/site-packages/yaml/composer.py", line 82, in compose_node
2020-07-16T17:07:52.1632917Z     node = self.compose_sequence_node(anchor)
2020-07-16T17:07:52.1633195Z   File "/usr/local/lib/python3.8/site-packages/yaml/composer.py", line 110, in compose_sequence_node
2020-07-16T17:07:52.1633520Z     while not self.check_event(SequenceEndEvent):
2020-07-16T17:07:52.1633840Z   File "/usr/local/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
2020-07-16T17:07:52.1633955Z     self.current_event = self.state()
2020-07-16T17:07:52.1634238Z   File "/usr/local/lib/python3.8/site-packages/yaml/parser.py", line 382, in parse_block_sequence_entry
2020-07-16T17:07:52.1634367Z     if self.check_token(BlockEntryToken):
2020-07-16T17:07:52.1634635Z   File "/usr/local/lib/python3.8/site-packages/yaml/scanner.py", line 116, in check_token
2020-07-16T17:07:52.1634756Z     self.fetch_more_tokens()
2020-07-16T17:07:52.1635010Z   File "/usr/local/lib/python3.8/site-packages/yaml/scanner.py", line 258, in fetch_more_tokens
2020-07-16T17:07:52.1635131Z     raise ScannerError("while scanning for the next token", None,
2020-07-16T17:07:52.1635247Z yaml.scanner.ScannerError: while scanning for the next token
2020-07-16T17:07:52.1635480Z found character '%' that cannot start any token
2020-07-16T17:07:52.1635588Z   in "<stdin>", line 8, column 4
```

**Comment by admiralAwkbar** [comment]
@tinder-yukisawa hello!
It seems that its a limitation of the `ymllint`.. you have 3 real options it seems:

https://github.com/github/super-linter/blob/master/docs/disabling-linters.md#yaml

I hope this helps :)

**Comment by tinder-yukisawa** [comment]
Hi @admiralAwkbar thanks for your help!
So I do have a `.yaml-lint.yml` file set to ignore any folders with Jinja templates but I think this error is happening before any linting occurs or before that config is loaded.

I guess one way to over come this is to `rm` any dirs like this before running the super-linter?

**Comment by admiralAwkbar** [comment]
@tinder-yukisawa  interesting... I will try to validate it loads the file and uses it... will test tomorrow if I can get a few cycles
thanks!

**Comment by admiralAwkbar** [comment]
@tinder-yukisawa seems we solved the issue :) please let me know if you find any issues! thanks!

**Comment by tinder-yukisawa** [comment]
@admiralAwkbar Thank you very much for the quick fix!
