### ISSUE TITLE
Terrascan HCL2 issue

### ISSUE THREAD

**Issue by jonesy1234** [github/super-linter#480]
**Describe the bug**
Terrascan does not currently support HCL2 from Hashicorp, due to this the linter throws errors. This is a known issue that is being tracked as part of https://github.com/accurics/terrascan/issues/233

**To Reproduce**
Perform linting run against terraform code containing something like the following

```
output instance_details {
  description = "Details of instance "
  value = [
    for instance in aws_instance.instances :
    {
      name       = instance.tags.Name
      id         = instance.id
      private_ip = instance.private_ip
    }
  ]
}
```

**Expected behavior**
Linting for all terraform language is performed without exception errors

**Screenshots**
See output extract below

**Additional context**
```

terrascan version 0.2.3
--
382 | Logging level set to error.
383 |  
384 | Processed 0 files in /codebuild/output/src135517985/src/****/****/****/.terrascan
385 |  
386 |  
387 | Processed on 07/26/2020 at 12:18
388 | Results (took 0.35 seconds):
389 |  
390 | Failures: (0)
391 |  
392 | Errors: (1)
393 | [high] Traceback (most recent call last):
394 | File "/usr/local/lib/python3.8/site-packages/terrascan/embedded/terraform_validate/terraform_validate.py", line 573, in readDir
395 | self.loadFileByDir(fileName, relativeFileName, d, d, terraform_string)
396 | File "/usr/local/lib/python3.8/site-packages/terrascan/embedded/terraform_validate/terraform_validate.py", line 594, in loadFileByDir
397 | self.loadFileByDir(fileName, path[1:], hclSubDirDict, parentDir, terraform_string)
398 | File "/usr/local/lib/python3.8/site-packages/terrascan/embedded/terraform_validate/terraform_validate.py", line 586, in loadFileByDir
399 | hclSubDirDict[path] = hcl.loads(terraform_string)
400 | File "/usr/local/lib/python3.8/site-packages/hcl/api.py", line 81, in loads
401 | return HclParser().parse(s, export_comments=export_comments)
402 | File "/usr/local/lib/python3.8/site-packages/hcl/parser.py", line 642, in parse
403 | return self.yacc.parse(
404 | File "/usr/local/lib/python3.8/site-packages/hcl/ply/yacc.py", line 503, in parse
405 | tok = self.errorfunc(errtoken)
406 | File "/usr/local/lib/python3.8/site-packages/hcl/parser.py", line 634, in p_error
407 | raise ValueError(msg)
408 | ValueError: Line 4, column 117: unexpected IDENTIFIER; expected ASTERISK_PERIOD, LEFTPAREN, COMMA, LEFTBRACKET, RIGHTBRACKET, RIGHTPAREN, ADD, MINUS, MULTIPLY, DIVIDE
409 | in file /codebuild/output/src135517985/src/****/****/****/.terrascan/outputs.tf]·[0m
410 | ·[0m·[41m·[0;37mERROR:·[0m Linter CMD:[terrascan -f  /codebuild/output/src135517985/src/****/****/****/****/****/outputs.tf]·[0m

**Comment by jonesy1234** [comment]
For the above issue it would be nice to be able to disable the terraform linters independently. Currently setting VALIDATE_TERRAFORM=false will prevent both tflint & terrascan from running.

**Comment by cesar-rodriguez** [comment]
Terrascan can be disabled without disabling tflint by setting ```VALIDATE_TERRAFORM_TERRASCAN=false```. The ```VALIDATE_TERRAFORM``` variable should only affect tflint.

**Comment by jonesy1234** [comment]
> Terrascan can be disabled without disabling tflint by setting `VALIDATE_TERRAFORM_TERRASCAN=false`. The `VALIDATE_TERRAFORM` variable should only affect tflint.

Great thanks, I didn't find that ref in the readme
