### ISSUE TITLE
Pylint: load-plugins in PYTHON_PYLINT_CONFIG_FILE

### ISSUE THREAD

**Issue by JuliusJacobitz** [github/super-linter#855]
Hi there,
I added `load-plugins=pylint_django` to my PYTHON_PYLINT_CONFIG_FILE.

After pushing I recieve the following error in Github Actions:

```
2020-10-15 12:28:11 [ERROR ]   [Traceback (most recent call last):
  File "/usr/local/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/usr/local/lib/python3.9/site-packages/pylint/__init__.py", line 22, in run_pylint
    PylintRun(sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/pylint/lint/run.py", line 308, in __init__
    linter.load_plugin_modules(plugins)
  File "/usr/local/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 490, in load_plugin_modules
    module = modutils.load_module_from_name(modname)
  File "/usr/local/lib/python3.9/site-packages/astroid/modutils.py", line 203, in load_module_from_name
    return load_module_from_modpath(dotted_name.split("."), path, use_sys)
  File "/usr/local/lib/python3.9/site-packages/astroid/modutils.py", line 244, in load_module_from_modpath
    mp_file, mp_filename, mp_desc = imp.find_module(part, path)
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'pylint_django']
```
Since I could not findy any way to install the missing module, is there a workaround or sth. I am missing ? 
Thanks for any help !

**Comment by ferrarimarco** [comment]
AFAIK, we don't currently have a way to install additional modules.

As a workaround, you might have to build your own container image and install what you need.

/cc @admiralAwkbar

**Comment by admiralAwkbar** [comment]
@ferrarimarco  @JuliusJacobitz I think the only other option is to use the rules to ignore the module load failures at this point...

**Comment by admiralAwkbar** [comment]
@JuliusJacobitz another option would be to clone the container, then load the plugins, then run it... that could work as well :)

**Comment by ferrarimarco** [comment]
> @JuliusJacobitz another option would be to clone the container, then load the plugins, then run it... that could work as well :)

That's what I was suggesting :)

You might go fancy and enable dependabot, so that every time super-linter gets a new version, you'll have a PR ready in your repo :)

**Comment by GaboFDC** [comment]
A bit late, but the easiest workaround is described in #157
